### ISSUE TITLE
package.json name attribute is invalid

### ISSUE THREAD

**Issue by danielfbm** [klarkc/polymer-loopback-starter-kit#1]
Hi. First thank you very much for taking your time to integrate this. It is exactly what I was looking for.

Now the issue: the name attribute has spaces. When I run 

``` bash
    npm install
```

It give some errors and doesn't finish installing, so I just removed the spaces from the name and it started installing

**Comment by klarkc** [comment]
Thank you, I fixed both bower and node package in the latest commit: 56ef14e0440766a2fb24db8322c3ae59ebc2dceb
