### ISSUE TITLE
Example using the lbclient.js in polymer

### ISSUE THREAD

**Issue by nigeltiany** [klarkc/polymer-loopback-starter-kit#3]
How can the browserified files(The loopback Isomer) be used in a polymer component.

``` html
<script src="src/loopback/scripts/lbclient.js"></script>
<link rel="import" href="/src/app.html">
<body>
    <my-app></my-app>
</body>
```

``` html
<dom-module id="my-app">
    <template>
    <script>
        Polymer({
            is: 'my-app',
            authenticate: function () {
                //Call User method defined in the server ---> undefined
                User.create();
            }
        });
    </script>
</dom-module>
```

---

``` html
<link rel="import" href="src/loopback/scripts/lbclient.html">
<link rel="import" href="/src/app.html">
<body>
    <my-app></my-app>
</body>
```

``` html
<!--lbclient.html-->
<script src="lbclient.js"></script>
```

``` javascript
Polymer({
   is: 'my-app',
   authenticate: function () {
        //Call User method defined in the server ---> undefined
        User.create();
    }
});
```

 @klarkc

**Comment by klarkc** [comment]
Hello, sorry for the delay. You are right, this information is missing in README. There is a task in gulp, called `lbclient`, this task build the `bundle.js` file with content from `client/loopback` in `client/scripts/bundle.js`. This file is loaded at `client/index.html:55`. So to use the models you just require the lbclient anywhere, like:

``` js
<script> 
  var app = require('lbclient'); 
  var User = app.models.User;
  User.login({
    email: 'test@example.com',
    password: '12345'
  }, function(err, res) {
    if (err) {
      console.error('Login failed: ', err);
    } else {
      console.log('Logged in.');
    }
  });
</script>
```

You can have the docs regarding this here:
https://github.com/klarkc/polymer-loopback-starter-kit#loopback
https://docs.strongloop.com/display/public/LB/Running+LoopBack+in+the+browser

**Comment by nigeltiany** [comment]
Yeah, i found that later in the docs. But somewhere in the 100,000+ lines of code there are errors. I think it was `fs.readfilesync is not a function` error and `fs.readaddr is not a function` error. Haven't found a way to solve this yet. not an issue related to this kit but have you encountered and solved this error?
I tried using `b.transform('bfrs');` before piping out to the file. This didn't work. [brfs](https://github.com/substack/brfs) @klarkc

**Comment by klarkc** [comment]
Strange, for me it is working, Did you tried to clean the bundle and create again? `$ gulp clean`

**Comment by klarkc** [comment]
Look at [testing-lbclient](/klarkc/polymer-loopback-starter-kit/compare/testing-lbclient) for an working example here

**Comment by klarkc** [comment]
@Nigeltiany Maybe it's related to the browserify version, or even node.js version. Are you trying with the latest versions of these packages?

**Comment by nigeltiany** [comment]
I have updated all packages `browserify 13.1.0` updated node `-v 6.5.0` did a `gulp clean` then `gulp serve` but still the errors persists. @klarkc

**Comment by klarkc** [comment]
@Nigeltiany , I tested here with exactly same versions, no problems :confused:

**Comment by klarkc** [comment]
BTW the issue with the size of bundle is already know, the strongloop team is working on it, for now wrapping whole loopback into the bundle is the only workaround. strongloop/loopback#989

**Comment by klarkc** [comment]
I suggest you to open an issue in loopback repo about browserify loopback and your specific error. I guess this occurs only in Windows, but I am not sure.

**Comment by klarkc** [comment]
I'll close this for now, fell free to re-open if you have any updates on this.
